version: '3.9'

services:
  app:
    image: glpinutec:v2.0
    volumes:
      - $(pwd)/etc_glpi:/etc/glpi
      - $(pwd)/lib_glpi:/var/lib/glpi
      - $(pwd)/log_glpi:/var/log/glpi
      - $(pwd)/log_apache2:/var/log/apache2
      - $(pwd)/glpi_marketplace:/var/www/html/marketplace
    networks:
      - glpi-net
    healthcheck:
      test: [ 'CMD', '/healthcheck.sh' ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 10s
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s

  db:
    image: mariadb:11.0.2
    volumes:
      - $(pwd)/lib-mysql:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/glpisec-dbroot-passwd
      - MARIADB_ROOT_HOST=localhost
      - MARIADB_USER=
      - MARIADB_PASSWORD_FILE=/run/secrets/glpisec-dbuser-passwd
      - MARIADB_DATABASE=
    networks:
      - glpi-net
    secrets:
      - glpisec-dbroot-passwd
      - glpisec-dbuser-passwd
    healthcheck:
      test:
        [
          'CMD',
          'mariadb-admin',
          'ping',
          '--host=localhost',
          '--user=root'
        ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 10s
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s

secrets:
  glpisec-dbroot-passwd:
    external: true
  glpisec-dbuser-passwd:
    external: true

networks:
  glpi-net:
    name: glpi-net
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/28
