version: '3.9'

services:
  app:
    build:
      context: ./app/
    container_name: glpi-app
    #ports:
    #  - '80:80'
    volumes:
      - $(pwd)/etc_glpi:/etc/glpi
      - $(pwd)/lib_glpi:/var/lib/glpi
      - $(pwd)/log_glpi:/var/log/glpi
      - $(pwd)/log_apache2:/var/log/apache2
      - $(pwd)/glpi_marketplace:/var/www/html/marketplace
    networks:
      - glpi-net
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'curl', '-fsI', 'http://localhost' ]
      interval: 3m
      timeout: 30s
      retries: 3
      start_period: 30s

  db:
    image: mariadb:11.0.2
    container_name: glpi-db
    #ports:
    #  - '127.0.0.1:3306:3306'
    volumes:
      - $(pwd)/lib-mysql:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=
      - MARIADB_ROOT_HOST=localhost
      - MARIADB_USER=
      - MARIADB_PASSWORD=
      - MARIADB_DATABASE=
    networks:
      - glpi-net
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'mariadb-admin',
          'ping',
          '--host=localhost',
          '--user=root'
        ]
      interval: 3m
      timeout: 30s
      retries: 3
      start_period: 30s

networks:
  glpi-net:
    name: glpi-net
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/28
