version: "3.9"

services:
  glpi:
    build:
      context: ./main/
      args:
        - PATH_CONF_STORE=/etc/glpi
        - PATH_DATA_STORE=/var/lib/glpi
        - PATH_LOG_STORE=/var/log/glpi
    ports:
      - "5000:80"
    depends_on:
      - glpi-db
    networks:
      glpi-net:
        ipv4_address: 172.16.1.3
    restart: always
    #healthcheck:
    #  test: [ "CMD", "curl", "-f", "http://localhost:5000" ]
    #  interval: 3m
    #  timeout: 30s
    #  retries: 5
    #  start_period: 30s
    container_name: glpi
    volumes:
      - ~/glpi-storage/config:/etc/glpi
      - ~/glpi-storage/data:/var/lib/glpi
      - ~/glpi-storage/log:/var/log/glpi
    # - ./main/glpi/install:/var/www/html/install

  glpi-db:
    image: mariadb:10.8.3
    ports:
      - "127.0.0.1:3306:3306"
    env_file:
      - ./database/.env
    networks:
      glpi-net:
        ipv4_address: 172.16.1.2
    restart: always
    #healthcheck:
    #  test:
    #    [
    #      "CMD",
    #      "mysqladmin",
    #      "ping",
    #      "-h",
    #      "127.0.0.1",
    #      "-u",
    #      "root",
    #      "--password=$$MARIADB_ROOT_PASSWORD"
    #    ]
    #  interval: 3m
    #  timeout: 30s
    #  retries: 5
    #  start_period: 30s
    container_name: glpi-db
    volumes:
      - ~/glpi-storage/database:/var/lib/mysql

networks:
  glpi-net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.1.0/24"
