CREATE USER IF NOT EXISTS `$USERNAME`@`$HOST` IDENTIFIED BY `$PASSOWRD`;

GRANT SHOW DATABASES ON *.* TO `$USERNAME`@`$HOST` IDENTIFIED BY `$PASSOWRD`;

GRANT
    ALTER,
    CREATE,
    CREATE VIEW,
    DROP,
    CREATE TEMPORARY TABLES,
    CREATE ROUTINE,
    EVENT,
    LOCK TABLES,
    INSERT,
    DELETE,
    UPDATE,
    SELECT,
    INDEX,
    REFERENCES,
    SHOW VIEW,
    TRIGGER
ON $DB_NAME.* TO `$USERNAME`@`$HOST` IDENTIFIED BY `$PASSOWRD`;


REVOKE
    ALTER,
    CREATE,
    CREATE VIEW,
    DROP,
    CREATE ROUTINE,
    REFERENCES
ON $DB_NAME.* FROM  `$USERNAME`@`$HOST`;